[project]
name = 'Lendy'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.collateral]
path = 'contracts/collateral.clar'
clarity_version = 2
epoch = 2.5

[contracts.interest]
path = 'contracts/interest.clar'
clarity_version = 2
epoch = 2.5

[contracts.issuance]
path = 'contracts/issuance.clar'
clarity_version = 2
epoch = 2.5

[contracts.liquidation]
path = 'contracts/liquidation.clar'
clarity_version = 2
epoch = 2.5

[contracts.repayment]
path = 'contracts/repayment.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
